app = "fly-ws-forwarder"

kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"
  GO_ENV = "production"

[build]
  builder = "paketobuildpacks/builder:base"

[metrics]
  port = 8080
  path = "/metrics"

[deploy]
  strategy = "rolling"
  max_unavailable = 0

[experimental]
  auto_rollback = true
  enable_consul = true

[[services]]
  internal_port = 8080
  protocol = "http"

  [services.concurrency]
    type = "connections"
    soft_limit = 100
    hard_limit = 150

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "10s"
    timeout = "3s"
    method = "head"
    path = "/healthz"
    protocol = "http"
    restart_limit = 5
    grace_period = "15s"

[vm]
  memory = "512mb"
  cpus = 2
